<?php

include_once('BluePHP/BlueSystem/GUI/Forms.inc');
include_once('BluePHP/BlueSystem/GUI/CommonOps.inc');
include_once('BluePHP/BlueSystem/GUI/BSGTemplate.inc');

include_once('BluePHP/BlueSystem/Tools/BSConstant.inc');
include_once('BluePHP/BlueSystem/Tools/BSPropertyFile.inc');
include_once('BluePHP/BlueSystem/Tools/BSbasetools.inc');
include_once('BluePHP/BlueSystem/Tools/BSLanguage.inc');

$params = extractParamFromGetOrArgv($argv);

?>
