<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<title>Blue Eye Video - CIR Generator</title>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<link rel="stylesheet" type="text/css" href="/BlueProjectPHP/styles/blueeyevideo.css"/>
<script language="JavaScript" SRC="/BlueProjectPHP/libraries/BlueAjax.js"></script> 
</head>
<body>
