<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<title>BlueEyeVideo system - main page</title>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1" />
<link rel="stylesheet" type="text/css" href="styles/blueeyevideo.css"/>
<link rel="stylesheet" type="text/css" href="/BlueSystem/styles/StyleBlueEyeVideo.css"/>
<script language="JavaScript" SRC="js/AnchorPosition.js"></script>
<script language="JavaScript" SRC="js/PopupWindow.js"></script>
<script language="JavaScript" SRC="js/date.js"></script>
<script language="JavaScript" SRC="js/CalendarPopup.js"></script>
</head>
<body>
<div id="main">
<div id="top">
<table class="head">
<tr>
<td><div id="logo"><img src="/BlueSystem/styles/LogoStyle.gif" alt="logo BEV"/></div></td>
<td><div align="center"><h3>BlueCount Portail Rev. <?php echo VERSION ?></h3></div></td>
</tr>
</table>
</div>

<div id="desc">
<h1>

<?php echo $pageTitle; ?>

</h1>
